language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y
  - sudo apt-get install php5-cli
script:
  - npm test
